server:
  port: 9100
  tomcat:
    uri-encoding: UTF-8

# datasource
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/ayoue?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: ayoue
      password: 123456
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
  sessions: ALWAYS
  oauth2:
      sso:
        loginPath: /login
      client:
        clientId: ssoclient
        clientSecret: ssosecret
        accessTokenUri: http://passport.ayoue.com/oauth/token
        userAuthorizationUri: http://passport.ayoue.com/oauth/authorize
        clientAuthenticationScheme: form
      resource:
        jwt:
          keyUri: http://passport.ayoue.com/oauth/token_key

securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /rest/**,/bb**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin